overrides:
  lodash: 4.18.1
  lodash-amd: 4.18.1
  lodash-es: 4.18.1
  lodash.unset: 4.18.0
  'brace-expansion@<2.0.0': 1.1.16
  'brace-expansion@>=2.0.0 <3.0.0': 2.1.2
  'brace-expansion@>=3.0.0 <6.0.0': 5.0.7
  'minimatch@>=9.0.0 <9.0.7': 9.0.7
  'eslint-plugin-barrel-files>oxc-resolver': 11.19.1
nodeLinker: 'hoisted'
